<Project Sdk="Godot.NET.Sdk/4.7.2">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <TargetFramework Condition=" '$(GodotTargetPlatform)' == 'android' ">net9.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <RootNamespace>BeyondTheWorlds</RootNamespace>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Content Include=".gitattributes" />
    <Content Include=".github\ISSUE_TEMPLATE\feature.yml" />
    <Content Include=".github\PULL_REQUEST_TEMPLATE.md" />
    <Content Include=".github\PULL_REQUEST_TEMPLATE.md.md" />
    <Content Include=".gitignore" />
    <Content Include=".git\COMMIT_EDITMSG" />
    <Content Include=".git\config" />
    <Content Include=".git\description" />
    <Content Include=".git\FETCH_HEAD" />
    <Content Include=".git\HEAD" />
    <Content Include=".git\hooks\applypatch-msg.sample" />
    <Content Include=".git\hooks\commit-msg.sample" />
    <Content Include=".git\hooks\fsmonitor-watchman.sample" />
    <Content Include=".git\hooks\post-update.sample" />
    <Content Include=".git\hooks\pre-applypatch.sample" />
    <Content Include=".git\hooks\pre-commit.sample" />
    <Content Include=".git\hooks\pre-merge-commit.sample" />
    <Content Include=".git\hooks\pre-push.sample" />
    <Content Include=".git\hooks\pre-rebase.sample" />
    <Content Include=".git\hooks\pre-receive.sample" />
    <Content Include=".git\hooks\prepare-commit-msg.sample" />
    <Content Include=".git\hooks\push-to-checkout.sample" />
    <Content Include=".git\hooks\sendemail-validate.sample" />
    <Content Include=".git\hooks\update.sample" />
    <Content Include=".git\index" />
    <Content Include=".git\info\exclude" />
    <Content Include=".git\info\refs" />
    <Content Include=".git\logs\HEAD" />
    <Content Include=".git\logs\refs\heads\869egez31" />
    <Content Include=".git\logs\refs\heads\BW-3\CardSys" />
    <Content Include=".git\logs\refs\heads\BW-50\HealthSys" />
    <Content Include=".git\logs\refs\heads\BW-54\Templates" />
    <Content Include=".git\logs\refs\heads\dev" />
    <Content Include=".git\logs\refs\heads\main" />
    <Content Include=".git\logs\refs\heads\switch" />
    <Content Include=".git\logs\refs\remotes\origin\BW-19" />
    <Content Include=".git\logs\refs\remotes\origin\BW-3\CardSys" />
    <Content Include=".git\logs\refs\remotes\origin\BW-53\DebugConsole" />
    <Content Include=".git\logs\refs\remotes\origin\BW-54\Templates" />
    <Content Include=".git\logs\refs\remotes\origin\dev" />
    <Content Include=".git\logs\refs\remotes\origin\HEAD" />
    <Content Include=".git\objects\00\5e060753072c114e303028912bf47599baa5c9" />
    <Content Include=".git\objects\01\dd0efdb6683db8c7cc7bdf509ef15fd63dd855" />
    <Content Include=".git\objects\03\9307256137d3f304c18809f08fc3fcb358ff85" />
    <Content Include=".git\objects\05\1d213d49137a1eaf6ae9a2293c9f9fa37027c9" />
    <Content Include=".git\objects\08\81e7a230999a337edf5de2ec34b74a1e9556ba" />
    <Content Include=".git\objects\0b\40222413b02d8c0b69e0e5a506aea2a8a8abf6" />
    <Content Include=".git\objects\0e\4a250772cc51e19ed7aa0c310001ef1f8cbbd3" />
    <Content Include=".git\objects\0e\d0cf751b92d219e28a29ee64b6a59e3f0b3d34" />
    <Content Include=".git\objects\10\517f5c8a71894aa8f13ad49988fbb8b16275ee" />
    <Content Include=".git\objects\10\b1e7a330aec65e57d27e2bfee98ca0d61b334c" />
    <Content Include=".git\objects\11\339d1a132fe9d9f0341614ade88a35a3738f09" />
    <Content Include=".git\objects\14\51448c492ef19a7139debe729f7a095703d097" />
    <Content Include=".git\objects\18\235dfbf21ad435a41712533da4e63fac2b5f01" />
    <Content Include=".git\objects\18\9aa753f35e4d9918bd213a14b77f799d04d6d1" />
    <Content Include=".git\objects\19\9c30b7ab03951b13e0b21be17224a801ea0dfe" />
    <Content Include=".git\objects\1d\2a04396ed4bdb3e237a03d51d4f83080554351" />
    <Content Include=".git\objects\1f\13047a5a27bddbcca13b3a0fda281430bb275a" />
    <Content Include=".git\objects\1f\5d8765e0e2d384755bbeb1e72770ad3c4a570c" />
    <Content Include=".git\objects\1f\f55b80130d2b19de361ba9a9b228951484b34e" />
    <Content Include=".git\objects\22\15401a9a5508a0bd9b9d812831f757595f8361" />
    <Content Include=".git\objects\23\d60a314b31a15f52f72560833b6709149414d7" />
    <Content Include=".git\objects\27\a1e85254280a291b8e9ab40e908d758698cc53" />
    <Content Include=".git\objects\28\b0757afbb98009ef3477e912191c0a5cc1998d" />
    <Content Include=".git\objects\29\88fc306bb632520c19e279ba207e1bbb181c4f" />
    <Content Include=".git\objects\2b\3f2ac70c7afc1e6c52ee87e8366a02b708a6fd" />
    <Content Include=".git\objects\2d\50393f61b21f67bb6647be9176631be98002cc" />
    <Content Include=".git\objects\2e\a4b423a5fe4de38c3fe356debf931ddbe27d65" />
    <Content Include=".git\objects\2f\03a7a631ed8f0d823ea04a0b8595629eeae984" />
    <Content Include=".git\objects\2f\c07e474fa50814ca8603e06b32e0edcd6050ad" />
    <Content Include=".git\objects\30\5fa8b73d3dfdb5e7513591279b8a99924fa236" />
    <Content Include=".git\objects\31\e74b0d2f44ddcdb68d0203a608f682248ecd81" />
    <Content Include=".git\objects\33\5751ccf30f49e21392149add254586a205bc07" />
    <Content Include=".git\objects\33\c40858ac57557d4795b00ee211167c76fc911c" />
    <Content Include=".git\objects\33\d8bb1de5e6137fe9158effb8eee788dd0e20db" />
    <Content Include=".git\objects\37\a2dacc1d3e8bb6c9f0ace669c1fd4fbdac4a68" />
    <Content Include=".git\objects\39\44fa112d6ebd69edae51102f638f536ac06583" />
    <Content Include=".git\objects\40\f049ba99d44c12ef52e69ab50af543e1504d5c" />
    <Content Include=".git\objects\41\2a316c284e4e4e7fc6e10b7b822b0bd1e0cddb" />
    <Content Include=".git\objects\44\fa2de76aa95c562f2cd3a4bfcfa59a546e833a" />
    <Content Include=".git\objects\48\4a784586acb34f6bc39f736c210130211e60db" />
    <Content Include=".git\objects\49\dfbd7eed298f237093c2995eab0eb03a3e5523" />
    <Content Include=".git\objects\4a\2df21941220c99301b98f5401da867bbf50568" />
    <Content Include=".git\objects\4b\481a90eb525d3e4237488784e0ad64932fa3a5" />
    <Content Include=".git\objects\51\51cc400c82c2f1b334fd0021a0beff97a928bf" />
    <Content Include=".git\objects\54\5706c9806929e695a774824ef360679134f999" />
    <Content Include=".git\objects\54\b18debd1103e4996341ea8330a23259f08d27f" />
    <Content Include=".git\objects\54\dcf888527a2b26ec41bbb9ec6e26f18aca77ca" />
    <Content Include=".git\objects\5d\902fd74656ff04639b01c39e9c4f18b9b9c896" />
    <Content Include=".git\objects\5f\fa6959dbb4ebeccad46c4a954077c21f80eb93" />
    <Content Include=".git\objects\5f\fa74b9c401529bac4cc6e5e2890fad87bc298b" />
    <Content Include=".git\objects\61\bcef902e5e0fecb9ca22f5b14de56078b808d1" />
    <Content Include=".git\objects\62\c602813621850a6942909cb8975a9a9088b24e" />
    <Content Include=".git\objects\63\c298ddb88c5c7e0ecf08f091a752e0f198af4f" />
    <Content Include=".git\objects\65\f8942aed376f5c64fadba5f8b83f26b9cfc34f" />
    <Content Include=".git\objects\68\6c3f0ac7af44bcaa7132a6edf524e41f29ff27" />
    <Content Include=".git\objects\69\a5c6cd5f10ae7f0a51fbeb02a2ef14bf21d7b1" />
    <Content Include=".git\objects\6d\77701e908d6ea099fa4f9c8a29ed182f90c67c" />
    <Content Include=".git\objects\72\a76ed2c5d675b204e30556ac697fae9c5a592f" />
    <Content Include=".git\objects\73\867e426eee30a9b0c6cc06725fe7fcc2b5a5ba" />
    <Content Include=".git\objects\74\c249af125c0afc9cf9d452af206bd6bcb614e8" />
    <Content Include=".git\objects\75\eb7667527d4a388b6eb9854be3c987c4ddc8aa" />
    <Content Include=".git\objects\76\5845ec6d688ca01e764c4b56bc88cf0410834d" />
    <Content Include=".git\objects\76\9824a920ed6c0c42c77636daa6bae760f179f4" />
    <Content Include=".git\objects\76\ba663653d1d2ee92fe22235eb9a1a3e2e08a75" />
    <Content Include=".git\objects\77\dddb50612f368005df112098a3e1bbddfe90fc" />
    <Content Include=".git\objects\78\8855b129321e7f9b77ebb8faa6b6ac490628a5" />
    <Content Include=".git\objects\79\c865d78aaff8ebba8f7408576aed060cbb4798" />
    <Content Include=".git\objects\7a\2d04a551b845d8163cdb1a8f846644ed545e97" />
    <Content Include=".git\objects\7d\d0214a4686c9a5b15c8d44815dc562e2bf9dc0" />
    <Content Include=".git\objects\7d\d7853aba72c3e0cbfbc324cc9f80ae0f536c88" />
    <Content Include=".git\objects\7e\948c7ff324c185b602492219128ad3c6792341" />
    <Content Include=".git\objects\81\086b515da526baa75abea4e96bc98ca03424bb" />
    <Content Include=".git\objects\83\db98c8aec230afa0dbb231dc585f0529e68c6e" />
    <Content Include=".git\objects\86\0ea3837937af3633618a2e96b7a43e364ee891" />
    <Content Include=".git\objects\8a\711b0754170e0b7004ecd797f29efb4c018536" />
    <Content Include=".git\objects\8b\121c809d42bd4e604f55a704c3da82c01c86d3" />
    <Content Include=".git\objects\8c\43cd2d1cabb8d12505a8998f1f18cf494f53c4" />
    <Content Include=".git\objects\8c\9d4ee4e7f83f20e1a5abd7e458462e3cb991b7" />
    <Content Include=".git\objects\8c\a2ebba74995d4b43c0962eb6ce7663661cef61" />
    <Content Include=".git\objects\8e\2b5fc768f02e234463b494aabd7c5cb1a95749" />
    <Content Include=".git\objects\94\07162f71c5a90c68c35860363a5b6244ec34f4" />
    <Content Include=".git\objects\95\75fba7641659e2e865348ca9596baabb6b10eb" />
    <Content Include=".git\objects\9b\d9fcb4a10ce8d7f465da08a33814c305cb7439" />
    <Content Include=".git\objects\a0\77a623f317220ab938947bbbacd88d22bccef6" />
    <Content Include=".git\objects\a2\ed42f01783be715dd0139dc7b654bf2805998d" />
    <Content Include=".git\objects\a3\b2dab4d61ae2490840f47c8f2923bfbc118f15" />
    <Content Include=".git\objects\a5\058f033166b10e7c67ed31e36a5e42102dea6d" />
    <Content Include=".git\objects\a5\e530bcea9597fe416c75d90c7c7b6bd66f3af9" />
    <Content Include=".git\objects\a6\f6eea32c7a3c2539669189a20cbddef5f079ef" />
    <Content Include=".git\objects\a7\38fe9e757e4107470c49ce7d865f4d4246b8ae" />
    <Content Include=".git\objects\aa\de0b6a20265bde1a63d1e8dd3c45af4f72208f" />
    <Content Include=".git\objects\aa\e92e67be067576732654e20524ff7cf5d4af3d" />
    <Content Include=".git\objects\ac\f505446bf41f1322cc012f29d031d8a55ccc4b" />
    <Content Include=".git\objects\b0\15b39b9c53d9c9930784a5d33cfd73cedb538e" />
    <Content Include=".git\objects\b8\87f460c5a323ab81fc82520ba991d6c09138a5" />
    <Content Include=".git\objects\b8\c53cb50dec097c3a363ec837e525af8b4faf4e" />
    <Content Include=".git\objects\b9\71a2a9f70675facf8175b6eee24451ab96f115" />
    <Content Include=".git\objects\ba\3f81a2c270d6d01e9ab5afbae11bda63ac996f" />
    <Content Include=".git\objects\ba\83e0c3d7090216ab4c3fe3c09fba1c3cd898da" />
    <Content Include=".git\objects\bf\7295e2a535ff7f7d2ce22b4e98d257af61f936" />
    <Content Include=".git\objects\bf\ede8fc924de02fc6a105f0baf151402669c2a5" />
    <Content Include=".git\objects\c1\f86e3a89663f9980b74f8960bcca5a71961dc0" />
    <Content Include=".git\objects\c2\c6b784a95f441d9359db77d0d70be6b6cd8416" />
    <Content Include=".git\objects\c3\fd0cda7e18f0d75e91f8f22e1ffd03a4cc5bb0" />
    <Content Include=".git\objects\c8\038e5f10ced1e42b786468d235be86ca72ba0a" />
    <Content Include=".git\objects\ce\79f5ef1394222489017b42d06038552b343f90" />
    <Content Include=".git\objects\d0\9553bb1cdfb70369e0fae58aaacaedf1465a2c" />
    <Content Include=".git\objects\d2\ae0eb5668aa94b34e2a80c9b0ba6c1e03038d6" />
    <Content Include=".git\objects\d8\b5441c612cdc8986253c2215ddbeaef50329e8" />
    <Content Include=".git\objects\d9\a684de5f53bea9e103a431ece1d486445ef127" />
    <Content Include=".git\objects\da\200a37b0af78571c241f27047a7417be823d12" />
    <Content Include=".git\objects\df\7f70d0df8650621e1a381143e4b08506b5e750" />
    <Content Include=".git\objects\df\c7529f441e3ae5986ab62ebe21bbe899b2f5c8" />
    <Content Include=".git\objects\e1\b011599fae68286e5910735e4b26da4e3fe0aa" />
    <Content Include=".git\objects\e1\c84d92cf57a1c558079f13dbacf1aedfffeacd" />
    <Content Include=".git\objects\e2\0305e824d808eeeca9238ddaef59ec339ba993" />
    <Content Include=".git\objects\e3\20752f29fc464141ffa58e011b0bff96c5b783" />
    <Content Include=".git\objects\e5\36bb821ce65de8d815e910a26b012dad1d520b" />
    <Content Include=".git\objects\e6\4c8ffd3bb4f969e217dc8582c89ea4ea9a1811" />
    <Content Include=".git\objects\e7\7f8da712a8d63ed4f71eaf10f15c834e821a89" />
    <Content Include=".git\objects\e7\c7cf3cb7fe43dc9772c37e3984df3ad4b209ff" />
    <Content Include=".git\objects\e8\a5c21b4b3bbe09414814a20a1b5724729c623d" />
    <Content Include=".git\objects\e8\a8b9425992ce97fa36ab8b4db32e2ecf1979f4" />
    <Content Include=".git\objects\e9\d25efa4edcd3f35cb39eb1c332dc23d5d5433b" />
    <Content Include=".git\objects\eb\2c6cf05b8bbfd636a2808ef8fd56003d06a631" />
    <Content Include=".git\objects\ec\70305a5f6df2ad058286e6a92e3f1b448e3c19" />
    <Content Include=".git\objects\ec\afc309b25c9e74de4fc0b1579893db135215d2" />
    <Content Include=".git\objects\ee\740ca462f86cf0fe9a0680df19fc2bc2110628" />
    <Content Include=".git\objects\f1\b383b1bff64e3a96d1077e1e0166a41ccb0345" />
    <Content Include=".git\objects\f1\f7113f85a385851e30dfaf998000b58831dfaa" />
    <Content Include=".git\objects\f2\88e02732f422c96b7ce3136afd9495baf5b5d1" />
    <Content Include=".git\objects\f4\11e36d17217757911e58d3bff6d249623abc0c" />
    <Content Include=".git\objects\f8\6ee75e5f438ca360969ceb039853fb707c176a" />
    <Content Include=".git\objects\f9\edbadedd9428ff8b32128e559a2d77608c7100" />
    <Content Include=".git\objects\fb\c9160640a6b517382cacf7ee87f6f5151d01b8" />
    <Content Include=".git\objects\fe\5542b77581a201b100c806921ff2a2f937ea50" />
    <Content Include=".git\objects\ff\39f244e373c10aef90766019a15a86686ff5a2" />
    <Content Include=".git\objects\info\packs" />
    <Content Include=".git\objects\pack\multi-pack-index" />
    <Content Include=".git\objects\pack\pack-4413208e76888bdbc737346610d3352d935e983e.idx" />
    <Content Include=".git\objects\pack\pack-4413208e76888bdbc737346610d3352d935e983e.pack" />
    <Content Include=".git\objects\pack\pack-4413208e76888bdbc737346610d3352d935e983e.rev" />
    <Content Include=".git\objects\pack\pack-5d86a0e6c147da777f69415a4a9ac18d09c03762.idx" />
    <Content Include=".git\objects\pack\pack-5d86a0e6c147da777f69415a4a9ac18d09c03762.pack" />
    <Content Include=".git\objects\pack\pack-5d86a0e6c147da777f69415a4a9ac18d09c03762.rev" />
    <Content Include=".git\objects\pack\pack-f4884bc80cf287cfc1e5146002f87ab8d0d86abf.idx" />
    <Content Include=".git\objects\pack\pack-f4884bc80cf287cfc1e5146002f87ab8d0d86abf.mtimes" />
    <Content Include=".git\objects\pack\pack-f4884bc80cf287cfc1e5146002f87ab8d0d86abf.pack" />
    <Content Include=".git\objects\pack\pack-f4884bc80cf287cfc1e5146002f87ab8d0d86abf.rev" />
    <Content Include=".git\ORIG_HEAD" />
    <Content Include=".git\packed-refs" />
    <Content Include=".git\refs\heads\869egez31" />
    <Content Include=".git\refs\heads\BW-3\CardSys" />
    <Content Include=".git\refs\heads\BW-50\HealthSys" />
    <Content Include=".git\refs\heads\BW-54\Templates" />
    <Content Include=".git\refs\heads\dev" />
    <Content Include=".git\refs\heads\main" />
    <Content Include=".git\refs\heads\switch" />
    <Content Include=".git\refs\remotes\origin\BW-19" />
    <Content Include=".git\refs\remotes\origin\BW-3\CardSys" />
    <Content Include=".git\refs\remotes\origin\BW-53\DebugConsole" />
    <Content Include=".git\refs\remotes\origin\BW-54\Templates" />
    <Content Include=".git\refs\remotes\origin\dev" />
    <Content Include=".git\refs\remotes\origin\HEAD" />
    <Content Include=".idea\.idea.Beyond The Worlds\.idea\.gitignore" />
    <Content Include=".idea\.idea.Beyond The Worlds\.idea\.name" />
    <Content Include=".idea\.idea.Beyond The Worlds\.idea\encodings.xml" />
    <Content Include=".idea\.idea.Beyond The Worlds\.idea\indexLayout.xml" />
    <Content Include=".idea\.idea.Beyond The Worlds\.idea\libraries\GdSdk.xml" />
    <Content Include=".idea\.idea.Beyond The Worlds\.idea\projectSettingsUpdater.xml" />
    <Content Include=".idea\.idea.Beyond The Worlds\.idea\vcs.xml" />
    <Content Include=".idea\.idea.Beyond The Worlds\.idea\workspace.xml" />
    <Content Include="assets\test_card.png" />
    <Content Include="assets\test_card.png.import" />
    <Content Include="Beyond The Worlds.sln" />
    <Content Include="project.godot" />
    <Content Include="README.md" />
    <Content Include="src\autoloads\Events.cs.uid" />
    <Content Include="src\cards\CardBase.cs.uid" />
    <Content Include="src\cards\CardData.cs.uid" />
    <Content Include="src\cards\GraveyardManager.cs.uid" />
    <Content Include="src\cards\cards_bases\blood_mage.tres" />
    <Content Include="src\cards\cards_bases\test_card.tres" />
    <Content Include="src\cards\card_base.tscn" />
    <Content Include="src\cards\DeckManager.cs.uid" />
    <Content Include="src\cards\HandManager.cs.uid" />
    <Content Include="src\cards\TableManager.cs.uid" />
    <Content Include="src\common\orbital_cam\orbital_cam.gd" />
    <Content Include="src\common\orbital_cam\orbital_cam.gd.uid" />
    <Content Include="src\common\orbital_cam\orbital_cam.tscn" />
    <Content Include="src\enemies\Enemy.cs.uid" />
    <Content Include="src\enemies\Enemy.glb" />
    <Content Include="src\enemies\Enemy.glb.import" />
    <Content Include="src\enemies\enemy.tscn" />
    <Content Include="src\enemies\main.tscn" />
    <Content Include="src\enemies\SpawnSystem.cs.uid" />
    <Content Include="src\enemies\test_enemy.glb" />
    <Content Include="src\enemies\test_enemy.glb.import" />
    <Content Include="src\enemies\test_enemy.tscn" />
    <Content Include="src\levels\level_main.tscn" />
    <Content Include="src\levels\level_test\test_arena.gdshader.uid" />
    <Content Include="src\levels\level_test\test_arena.glb" />
    <Content Include="src\levels\level_test\test_arena.glb.import" />
    <Content Include="src\levels\level_test\test_arena.tscn" />
    <Content Include="src\player\PlayerHealth.cs.uid" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include=".git\objects\info\" />
    <Folder Include=".git\refs\tags\" />
    <Folder Include="addons\" />
    <Folder Include="src\enemies\bases\" />
    <Folder Include="src\enemies\components\" />
    <Folder Include="src\enemies\states\" />
  </ItemGroup>
</Project>
