<Project Sdk="Godot.NET.Sdk/4.7.0">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <TargetFramework Condition=" '$(GodotTargetPlatform)' == 'android' ">net9.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <RootNamespace>BeyondTheWorlds</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Content Include=".gitattributes" />
    <Content Include=".gitignore" />
    <Content Include=".git\COMMIT_EDITMSG" />
    <Content Include=".git\config" />
    <Content Include=".git\description" />
    <Content Include=".git\FETCH_HEAD" />
    <Content Include=".git\HEAD" />
    <Content Include=".git\hooks\applypatch-msg.sample" />
    <Content Include=".git\hooks\commit-msg.sample" />
    <Content Include=".git\hooks\fsmonitor-watchman.sample" />
    <Content Include=".git\hooks\post-update.sample" />
    <Content Include=".git\hooks\pre-applypatch.sample" />
    <Content Include=".git\hooks\pre-commit.sample" />
    <Content Include=".git\hooks\pre-merge-commit.sample" />
    <Content Include=".git\hooks\pre-push.sample" />
    <Content Include=".git\hooks\pre-rebase.sample" />
    <Content Include=".git\hooks\pre-receive.sample" />
    <Content Include=".git\hooks\prepare-commit-msg.sample" />
    <Content Include=".git\hooks\push-to-checkout.sample" />
    <Content Include=".git\hooks\sendemail-validate.sample" />
    <Content Include=".git\hooks\update.sample" />
    <Content Include=".git\index" />
    <Content Include=".git\info\exclude" />
    <Content Include=".git\info\refs" />
    <Content Include=".git\logs\HEAD" />
    <Content Include=".git\logs\refs\heads\BW-3\CardSys" />
    <Content Include=".git\logs\refs\heads\BW-50\HealthSys" />
    <Content Include=".git\logs\refs\heads\BW-54\Templates" />
    <Content Include=".git\logs\refs\heads\dev" />
    <Content Include=".git\logs\refs\heads\main" />
    <Content Include=".git\logs\refs\heads\switch" />
    <Content Include=".git\logs\refs\remotes\origin\BW-19" />
    <Content Include=".git\logs\refs\remotes\origin\BW-3\CardSys" />
    <Content Include=".git\logs\refs\remotes\origin\BW-53\DebugConsole" />
    <Content Include=".git\logs\refs\remotes\origin\BW-54\Templates" />
    <Content Include=".git\logs\refs\remotes\origin\dev" />
    <Content Include=".git\logs\refs\remotes\origin\HEAD" />
    <Content Include=".git\objects\00\5e060753072c114e303028912bf47599baa5c9" />
    <Content Include=".git\objects\01\dd0efdb6683db8c7cc7bdf509ef15fd63dd855" />
    <Content Include=".git\objects\03\9307256137d3f304c18809f08fc3fcb358ff85" />
    <Content Include=".git\objects\05\1d213d49137a1eaf6ae9a2293c9f9fa37027c9" />
    <Content Include=".git\objects\08\81e7a230999a337edf5de2ec34b74a1e9556ba" />
    <Content Include=".git\objects\0b\40222413b02d8c0b69e0e5a506aea2a8a8abf6" />
    <Content Include=".git\objects\0e\4a250772cc51e19ed7aa0c310001ef1f8cbbd3" />
    <Content Include=".git\objects\0e\d0cf751b92d219e28a29ee64b6a59e3f0b3d34" />
    <Content Include=".git\objects\10\517f5c8a71894aa8f13ad49988fbb8b16275ee" />
    <Content Include=".git\objects\10\b1e7a330aec65e57d27e2bfee98ca0d61b334c" />
    <Content Include=".git\objects\11\339d1a132fe9d9f0341614ade88a35a3738f09" />
    <Content Include=".git\objects\14\51448c492ef19a7139debe729f7a095703d097" />
    <Content Include=".git\objects\18\235dfbf21ad435a41712533da4e63fac2b5f01" />
    <Content Include=".git\objects\18\9aa753f35e4d9918bd213a14b77f799d04d6d1" />
    <Content Include=".git\objects\19\9c30b7ab03951b13e0b21be17224a801ea0dfe" />
    <Content Include=".git\objects\1d\2a04396ed4bdb3e237a03d51d4f83080554351" />
    <Content Include=".git\objects\1f\13047a5a27bddbcca13b3a0fda281430bb275a" />
    <Content Include=".git\objects\1f\5d8765e0e2d384755bbeb1e72770ad3c4a570c" />
    <Content Include=".git\objects\1f\f55b80130d2b19de361ba9a9b228951484b34e" />
    <Content Include=".git\objects\22\15401a9a5508a0bd9b9d812831f757595f8361" />
    <Content Include=".git\objects\23\d60a314b31a15f52f72560833b6709149414d7" />
    <Content Include=".git\objects\27\a1e85254280a291b8e9ab40e908d758698cc53" />
    <Content Include=".git\objects\28\b0757afbb98009ef3477e912191c0a5cc1998d" />
    <Content Include=".git\objects\29\88fc306bb632520c19e279ba207e1bbb181c4f" />
    <Content Include=".git\objects\2b\3f2ac70c7afc1e6c52ee87e8366a02b708a6fd" />
    <Content Include=".git\objects\2d\50393f61b21f67bb6647be9176631be98002cc" />
    <Content Include=".git\objects\2e\a4b423a5fe4de38c3fe356debf931ddbe27d65" />
    <Content Include=".git\objects\2f\03a7a631ed8f0d823ea04a0b8595629eeae984" />
    <Content Include=".git\objects\2f\c07e474fa50814ca8603e06b32e0edcd6050ad" />
    <Content Include=".git\objects\30\5fa8b73d3dfdb5e7513591279b8a99924fa236" />
    <Content Include=".git\objects\31\e74b0d2f44ddcdb68d0203a608f682248ecd81" />
    <Content Include=".git\objects\33\5751ccf30f49e21392149add254586a205bc07" />
    <Content Include=".git\objects\33\c40858ac57557d4795b00ee211167c76fc911c" />
    <Content Include=".git\objects\33\d8bb1de5e6137fe9158effb8eee788dd0e20db" />
    <Content Include=".git\objects\37\a2dacc1d3e8bb6c9f0ace669c1fd4fbdac4a68" />
    <Content Include=".git\objects\39\44fa112d6ebd69edae51102f638f536ac06583" />
    <Content Include=".git\objects\40\f049ba99d44c12ef52e69ab50af543e1504d5c" />
    <Content Include=".git\objects\41\2a316c284e4e4e7fc6e10b7b822b0bd1e0cddb" />
    <Content Include=".git\objects\44\fa2de76aa95c562f2cd3a4bfcfa59a546e833a" />
    <Content Include=".git\objects\48\4a784586acb34f6bc39f736c210130211e60db" />
    <Content Include=".git\objects\49\dfbd7eed298f237093c2995eab0eb03a3e5523" />
    <Content Include=".git\objects\4a\2df21941220c99301b98f5401da867bbf50568" />
    <Content Include=".git\objects\4b\481a90eb525d3e4237488784e0ad64932fa3a5" />
    <Content Include=".git\objects\51\51cc400c82c2f1b334fd0021a0beff97a928bf" />
    <Content Include=".git\objects\54\5706c9806929e695a774824ef360679134f999" />
    <Content Include=".git\objects\54\b18debd1103e4996341ea8330a23259f08d27f" />
    <Content Include=".git\objects\54\dcf888527a2b26ec41bbb9ec6e26f18aca77ca" />
    <Content Include=".git\objects\5d\902fd74656ff04639b01c39e9c4f18b9b9c896" />
    <Content Include=".git\objects\5f\fa6959dbb4ebeccad46c4a954077c21f80eb93" />
    <Content Include=".git\objects\5f\fa74b9c401529bac4cc6e5e2890fad87bc298b" />
    <Content Include=".git\objects\61\bcef902e5e0fecb9ca22f5b14de56078b808d1" />
    <Content Include=".git\objects\62\c602813621850a6942909cb8975a9a9088b24e" />
    <Content Include=".git\objects\63\c298ddb88c5c7e0ecf08f091a752e0f198af4f" />
    <Content Include=".git\objects\65\f8942aed376f5c64fadba5f8b83f26b9cfc34f" />
    <Content Include=".git\objects\68\6c3f0ac7af44bcaa7132a6edf524e41f29ff27" />
    <Content Include=".git\objects\69\a5c6cd5f10ae7f0a51fbeb02a2ef14bf21d7b1" />
    <Content Include=".git\objects\6d\77701e908d6ea099fa4f9c8a29ed182f90c67c" />
    <Content Include=".git\objects\72\a76ed2c5d675b204e30556ac697fae9c5a592f" />
    <Content Include=".git\objects\73\867e426eee30a9b0c6cc06725fe7fcc2b5a5ba" />
    <Content Include=".git\objects\74\c249af125c0afc9cf9d452af206bd6bcb614e8" />
    <Content Include=".git\objects\75\eb7667527d4a388b6eb9854be3c987c4ddc8aa" />
    <Content Include=".git\objects\76\5845ec6d688ca01e764c4b56bc88cf0410834d" />
    <Content Include=".git\objects\76\9824a920ed6c0c42c77636daa6bae760f179f4" />
    <Content Include=".git\objects\76\ba663653d1d2ee92fe22235eb9a1a3e2e08a75" />
    <Content Include=".git\objects\77\dddb50612f368005df112098a3e1bbddfe90fc" />
    <Content Include=".git\objects\78\8855b129321e7f9b77ebb8faa6b6ac490628a5" />
    <Content Include=".git\objects\79\c865d78aaff8ebba8f7408576aed060cbb4798" />
    <Content Include=".git\objects\7a\2d04a551b845d8163cdb1a8f846644ed545e97" />
    <Content Include=".git\objects\7d\d0214a4686c9a5b15c8d44815dc562e2bf9dc0" />
    <Content Include=".git\objects\7d\d7853aba72c3e0cbfbc324cc9f80ae0f536c88" />
    <Content Include=".git\objects\7e\948c7ff324c185b602492219128ad3c6792341" />
    <Content Include=".git\objects\81\086b515da526baa75abea4e96bc98ca03424bb" />
    <Content Include=".git\objects\83\db98c8aec230afa0dbb231dc585f0529e68c6e" />
    <Content Include=".git\objects\86\0ea3837937af3633618a2e96b7a43e364ee891" />
    <Content Include=".git\objects\8a\711b0754170e0b7004ecd797f29efb4c018536" />
    <Content Include=".git\objects\8b\121c809d42bd4e604f55a704c3da82c01c86d3" />
    <Content Include=".git\objects\8c\43cd2d1cabb8d12505a8998f1f18cf494f53c4" />
    <Content Include=".git\objects\8c\9d4ee4e7f83f20e1a5abd7e458462e3cb991b7" />
    <Content Include=".git\objects\8c\a2ebba74995d4b43c0962eb6ce7663661cef61" />
    <Content Include=".git\objects\8e\2b5fc768f02e234463b494aabd7c5cb1a95749" />
    <Content Include=".git\objects\94\07162f71c5a90c68c35860363a5b6244ec34f4" />
    <Content Include=".git\objects\95\75fba7641659e2e865348ca9596baabb6b10eb" />
    <Content Include=".git\objects\9b\d9fcb4a10ce8d7f465da08a33814c305cb7439" />
    <Content Include=".git\objects\a0\77a623f317220ab938947bbbacd88d22bccef6" />
    <Content Include=".git\objects\a2\ed42f01783be715dd0139dc7b654bf2805998d" />
    <Content Include=".git\objects\a3\b2dab4d61ae2490840f47c8f2923bfbc118f15" />
    <Content Include=".git\objects\a5\058f033166b10e7c67ed31e36a5e42102dea6d" />
    <Content Include=".git\objects\a5\e530bcea9597fe416c75d90c7c7b6bd66f3af9" />
    <Content Include=".git\objects\a6\f6eea32c7a3c2539669189a20cbddef5f079ef" />
    <Content Include=".git\objects\a7\38fe9e757e4107470c49ce7d865f4d4246b8ae" />
    <Content Include=".git\objects\aa\de0b6a20265bde1a63d1e8dd3c45af4f72208f" />
    <Content Include=".git\objects\aa\e92e67be067576732654e20524ff7cf5d4af3d" />
    <Content Include=".git\objects\ac\f505446bf41f1322cc012f29d031d8a55ccc4b" />
    <Content Include=".git\objects\b0\15b39b9c53d9c9930784a5d33cfd73cedb538e" />
    <Content Include=".git\objects\b8\c53cb50dec097c3a363ec837e525af8b4faf4e" />
    <Content Include=".git\objects\b9\71a2a9f70675facf8175b6eee24451ab96f115" />
    <Content Include=".git\objects\ba\3f81a2c270d6d01e9ab5afbae11bda63ac996f" />
    <Content Include=".git\objects\ba\83e0c3d7090216ab4c3fe3c09fba1c3cd898da" />
    <Content Include=".git\objects\bf\7295e2a535ff7f7d2ce22b4e98d257af61f936" />
    <Content Include=".git\objects\bf\ede8fc924de02fc6a105f0baf151402669c2a5" />
    <Content Include=".git\objects\c1\f86e3a89663f9980b74f8960bcca5a71961dc0" />
    <Content Include=".git\objects\c2\c6b784a95f441d9359db77d0d70be6b6cd8416" />
    <Content Include=".git\objects\c3\fd0cda7e18f0d75e91f8f22e1ffd03a4cc5bb0" />
    <Content Include=".git\objects\c8\038e5f10ced1e42b786468d235be86ca72ba0a" />
    <Content Include=".git\objects\ce\79f5ef1394222489017b42d06038552b343f90" />
    <Content Include=".git\objects\d0\9553bb1cdfb70369e0fae58aaacaedf1465a2c" />
    <Content Include=".git\objects\d2\ae0eb5668aa94b34e2a80c9b0ba6c1e03038d6" />
    <Content Include=".git\objects\d8\b5441c612cdc8986253c2215ddbeaef50329e8" />
    <Content Include=".git\objects\d9\a684de5f53bea9e103a431ece1d486445ef127" />
    <Content Include=".git\objects\da\200a37b0af78571c241f27047a7417be823d12" />
    <Content Include=".git\objects\df\7f70d0df8650621e1a381143e4b08506b5e750" />
    <Content Include=".git\objects\df\c7529f441e3ae5986ab62ebe21bbe899b2f5c8" />
    <Content Include=".git\objects\e1\b011599fae68286e5910735e4b26da4e3fe0aa" />
    <Content Include=".git\objects\e1\c84d92cf57a1c558079f13dbacf1aedfffeacd" />
    <Content Include=".git\objects\e3\20752f29fc464141ffa58e011b0bff96c5b783" />
    <Content Include=".git\objects\e5\36bb821ce65de8d815e910a26b012dad1d520b" />
    <Content Include=".git\objects\e6\4c8ffd3bb4f969e217dc8582c89ea4ea9a1811" />
    <Content Include=".git\objects\e7\7f8da712a8d63ed4f71eaf10f15c834e821a89" />
    <Content Include=".git\objects\e7\c7cf3cb7fe43dc9772c37e3984df3ad4b209ff" />
    <Content Include=".git\objects\e8\a5c21b4b3bbe09414814a20a1b5724729c623d" />
    <Content Include=".git\objects\e8\a8b9425992ce97fa36ab8b4db32e2ecf1979f4" />
    <Content Include=".git\objects\e9\d25efa4edcd3f35cb39eb1c332dc23d5d5433b" />
    <Content Include=".git\objects\eb\2c6cf05b8bbfd636a2808ef8fd56003d06a631" />
    <Content Include=".git\objects\ec\70305a5f6df2ad058286e6a92e3f1b448e3c19" />
    <Content Include=".git\objects\ec\afc309b25c9e74de4fc0b1579893db135215d2" />
    <Content Include=".git\objects\ee\740ca462f86cf0fe9a0680df19fc2bc2110628" />
    <Content Include=".git\objects\f1\b383b1bff64e3a96d1077e1e0166a41ccb0345" />
    <Content Include=".git\objects\f1\f7113f85a385851e30dfaf998000b58831dfaa" />
    <Content Include=".git\objects\f2\88e02732f422c96b7ce3136afd9495baf5b5d1" />
    <Content Include=".git\objects\f4\11e36d17217757911e58d3bff6d249623abc0c" />
    <Content Include=".git\objects\f8\6ee75e5f438ca360969ceb039853fb707c176a" />
    <Content Include=".git\objects\f9\edbadedd9428ff8b32128e559a2d77608c7100" />
    <Content Include=".git\objects\fb\c9160640a6b517382cacf7ee87f6f5151d01b8" />
    <Content Include=".git\objects\fe\5542b77581a201b100c806921ff2a2f937ea50" />
    <Content Include=".git\objects\ff\39f244e373c10aef90766019a15a86686ff5a2" />
    <Content Include=".git\objects\info\packs" />
    <Content Include=".git\objects\pack\multi-pack-index" />
    <Content Include=".git\objects\pack\pack-4413208e76888bdbc737346610d3352d935e983e.idx" />
    <Content Include=".git\objects\pack\pack-4413208e76888bdbc737346610d3352d935e983e.pack" />
    <Content Include=".git\objects\pack\pack-4413208e76888bdbc737346610d3352d935e983e.rev" />
    <Content Include=".git\objects\pack\pack-f4884bc80cf287cfc1e5146002f87ab8d0d86abf.idx" />
    <Content Include=".git\objects\pack\pack-f4884bc80cf287cfc1e5146002f87ab8d0d86abf.mtimes" />
    <Content Include=".git\objects\pack\pack-f4884bc80cf287cfc1e5146002f87ab8d0d86abf.pack" />
    <Content Include=".git\objects\pack\pack-f4884bc80cf287cfc1e5146002f87ab8d0d86abf.rev" />
    <Content Include=".git\ORIG_HEAD" />
    <Content Include=".git\packed-refs" />
    <Content Include=".git\refs\heads\BW-3\CardSys" />
    <Content Include=".git\refs\heads\BW-50\HealthSys" />
    <Content Include=".git\refs\heads\BW-54\Templates" />
    <Content Include=".git\refs\heads\dev" />
    <Content Include=".git\refs\heads\main" />
    <Content Include=".git\refs\heads\switch" />
    <Content Include=".git\refs\remotes\origin\BW-19" />
    <Content Include=".git\refs\remotes\origin\BW-3\CardSys" />
    <Content Include=".git\refs\remotes\origin\BW-53\DebugConsole" />
    <Content Include=".git\refs\remotes\origin\BW-54\Templates" />
    <Content Include=".git\refs\remotes\origin\dev" />
    <Content Include=".git\refs\remotes\origin\HEAD" />
    <Content Include=".godot\.gdignore" />
    <Content Include=".godot\editor\AnimationComponent.cs-folding-035f38ab61d89a850e1b775f8b925f53.cfg" />
    <Content Include=".godot\editor\blood_mage.tres-folding-bfec542c780544ff76bb88905e750bba.cfg" />
    <Content Include=".godot\editor\BotStats.cs-folding-85a1bc894633534279fb2365bd1883e1.cfg" />
    <Content Include=".godot\editor\BotStats.tres-folding-0e067d4782acc766d10b72c1b6499e2d.cfg" />
    <Content Include=".godot\editor\Card.tres-folding-2504b593014afbcf2bd796ded86eede5.cfg" />
    <Content Include=".godot\editor\CardBase.cs-folding-a90e4c190ce8a4b699bd9843fcb9d3bf.cfg" />
    <Content Include=".godot\editor\CardData.cs-folding-6a31061ded7c12364b2213bd71cce307.cfg" />
    <Content Include=".godot\editor\CardData.cs-folding-8485fcf22b43a1690d7fadd4788a6304.cfg" />
    <Content Include=".godot\editor\CardData.tres-folding-7b2f600405b9085e0d26b4882e17722a.cfg" />
    <Content Include=".godot\editor\CardGraveyard.cs-folding-359f50817a5f82fc865febb57869fdd7.cfg" />
    <Content Include=".godot\editor\CardHand.cs-folding-fb3218cde3e869c9171e1a272a9f3500.cfg" />
    <Content Include=".godot\editor\CardManager.cs-folding-c7511029226d2c064eeb046b96cc6fff.cfg" />
    <Content Include=".godot\editor\CardsManager.cs-folding-8dfcb857530545ab0cb5ec8024d4315a.cfg" />
    <Content Include=".godot\editor\CardsManager.cs-folding-fe4b546cb9dab4671bf80fa96cf14c70.cfg" />
    <Content Include=".godot\editor\CardsResource.cs-folding-7af2df93dcd68c8cd12b7194e0176313.cfg" />
    <Content Include=".godot\editor\CardTemplate.cs-folding-9be6c75338aaf31b321c9d46bdce8df6.cfg" />
    <Content Include=".godot\editor\CardTemplate.cs-folding-c454123e697669f446ce19e39a3eb7b0.cfg" />
    <Content Include=".godot\editor\card_base.tscn-editstate-d33356d3a15b9f7bb8f0f88c7e67b840.cfg" />
    <Content Include=".godot\editor\card_base.tscn-folding-d33356d3a15b9f7bb8f0f88c7e67b840.cfg" />
    <Content Include=".godot\editor\CharacterBody2d.cs-folding-b71154b3067caa641b7249c2b40ebd90.cfg" />
    <Content Include=".godot\editor\create_recent.Node" />
    <Content Include=".godot\editor\create_recent.Resource" />
    <Content Include=".godot\editor\debug_console.tscn-editstate-337adc12b1b0bbe9d7ae5ce1a2ba74cc.cfg" />
    <Content Include=".godot\editor\debug_console.tscn-folding-337adc12b1b0bbe9d7ae5ce1a2ba74cc.cfg" />
    <Content Include=".godot\editor\debug_console_window.tscn-editstate-84bdc23f3a25cbfa4cf70a1a3ec3f7c9.cfg" />
    <Content Include=".godot\editor\debug_console_window.tscn-folding-84bdc23f3a25cbfa4cf70a1a3ec3f7c9.cfg" />
    <Content Include=".godot\editor\editor_layout.cfg" />
    <Content Include=".godot\editor\editor_script_doc_cache.res-folding-a7de57390d6e786984ca20c70a831128.cfg" />
    <Content Include=".godot\editor\Enemy.glb-eae58211c7bd6daea8ba9d0e776c3aae.scn-folding-380945f4921615f586e27c4cfd2f08c3.cfg" />
    <Content Include=".godot\editor\Exit.cs-folding-ca8422a1ea7d65b2a81b220ba03969c8.cfg" />
    <Content Include=".godot\editor\favorites" />
    <Content Include=".godot\editor\favorites.Node" />
    <Content Include=".godot\editor\favorites.Resource" />
    <Content Include=".godot\editor\favorite_properties" />
    <Content Include=".godot\editor\filesystem_cache10" />
    <Content Include=".godot\editor\filesystem_update4" />
    <Content Include=".godot\editor\fireball.tres-folding-3697ec676c7690258f76d62971d4d204.cfg" />
    <Content Include=".godot\editor\HealthSystem.cs-folding-6fa90080676c2239a6787d910fb0acaa.cfg" />
    <Content Include=".godot\editor\level_main.tscn-editstate-ccf2ad9ae959e5d65938d114f815eaec.cfg" />
    <Content Include=".godot\editor\level_main.tscn-folding-ccf2ad9ae959e5d65938d114f815eaec.cfg" />
    <Content Include=".godot\editor\main.tscn-editstate-23094c63a5a263f9092b895515665b57.cfg" />
    <Content Include=".godot\editor\main.tscn-folding-23094c63a5a263f9092b895515665b57.cfg" />
    <Content Include=".godot\editor\MasterDeck.cs-folding-d4d9ae4ca46895f3427eb498465e2831.cfg" />
    <Content Include=".godot\editor\MasterDeck.cs-folding-d9baf6ca41a72ba5e8d3ef2d57d26bfd.cfg" />
    <Content Include=".godot\editor\orbital_cam.gd-folding-609f5caed01e688b766b79c4b5a12589.cfg" />
    <Content Include=".godot\editor\orbital_cam.tscn-editstate-600a9af5e7a90a89e87c74205e383b52.cfg" />
    <Content Include=".godot\editor\orbital_cam.tscn-folding-600a9af5e7a90a89e87c74205e383b52.cfg" />
    <Content Include=".godot\editor\project_metadata.cfg" />
    <Content Include=".godot\editor\quick_open_dialog_cache.cfg" />
    <Content Include=".godot\editor\recent_dirs" />
    <Content Include=".godot\editor\script_editor_cache.cfg" />
    <Content Include=".godot\editor\TableManager.cs-folding-38a555f5f1505dc9dd0a889005658ba5.cfg" />
    <Content Include=".godot\editor\test_arena.glb-0f1507c80c3149da458e4b4d287d0c9e.scn-folding-b6575429c20620841145a1fa7a8913e0.cfg" />
    <Content Include=".godot\editor\test_card.tres-folding-3177509009ce42c0e33ecb366b390b5b.cfg" />
    <Content Include=".godot\editor\test_enemy.glb-9f10d29e8bc30b59312ae9067d72c219.scn-folding-943a1160a48fd83c1b4cd30313ff6b04.cfg" />
    <Content Include=".godot\global_script_class_cache.cfg" />
    <Content Include=".godot\imported\card.png-c12f80167372a8ea75cae1cb137b9cb2.ctex" />
    <Content Include=".godot\imported\card.png-c12f80167372a8ea75cae1cb137b9cb2.md5" />
    <Content Include=".godot\imported\card.png-ea74635cecca41fde9ff9361662de2cb.md5" />
    <Content Include=".godot\imported\Enemy.glb-eae58211c7bd6daea8ba9d0e776c3aae.md5" />
    <Content Include=".godot\imported\Enemy.glb-eae58211c7bd6daea8ba9d0e776c3aae.scn" />
    <Content Include=".godot\imported\test_arena.glb-0f1507c80c3149da458e4b4d287d0c9e.md5" />
    <Content Include=".godot\imported\test_arena.glb-0f1507c80c3149da458e4b4d287d0c9e.scn" />
    <Content Include=".godot\imported\test_card.png-dd52d148e99de95167450ee7b49c01b8.ctex" />
    <Content Include=".godot\imported\test_card.png-dd52d148e99de95167450ee7b49c01b8.md5" />
    <Content Include=".godot\imported\test_enemy.glb-9f10d29e8bc30b59312ae9067d72c219.md5" />
    <Content Include=".godot\imported\test_enemy.glb-9f10d29e8bc30b59312ae9067d72c219.scn" />
    <Content Include=".godot\scene_groups_cache.cfg" />
    <Content Include=".godot\shader_cache\BestFitNormalShaderRD\be7b506fb0d08c29b4041710889c21056b8092619f3689131a6dd641e054ad29\8305c75c1294a9f00656f0f14344bb8bedcfe4e7.vulkan.cache" />
    <Content Include=".godot\shader_cache\BlitShaderRD\60730ff5d181828d793048b679aedf660ec932db990c939f300e8875dc43b3cf\8305c75c1294a9f00656f0f14344bb8bedcfe4e7.vulkan.cache" />
    <Content Include=".godot\shader_cache\BokehDofShaderRD\9eecad1b8d87d91c2928400706561caf4a8a604a0ce721538bb779a2bc51f876\8305c75c1294a9f00656f0f14344bb8bedcfe4e7.vulkan.cache" />
    <Content Include=".godot\shader_cache\CanvasOcclusionShaderRD\c5cf7e62fd49f618cfdba96629de618a1b26be203d90def17606a90a4e91cf73\8305c75c1294a9f00656f0f14344bb8bedcfe4e7.vulkan.cache" />
    <Content Include=".godot\shader_cache\CanvasSdfShaderRD\cf39877e178c34ede4db342bbf1779a27125701d45df76cb3d07ef7c626416f2\8305c75c1294a9f00656f0f14344bb8bedcfe4e7.vulkan.cache" />
    <Content Include=".godot\shader_cache\CanvasShaderRD\9bdc1125c86af67021aafde8760184618f2961034b221ad5dbe673034858b1f3\8305c75c1294a9f00656f0f14344bb8bedcfe4e7.vulkan.cache" />
    <Content Include=".godot\shader_cache\CanvasShaderRD\9bdc1125c86af67021aafde8760184618f2961034b221ad5dbe673034858b1f3\89e0c5a264d1558e7bc2ca0dc3d0afd834fbe7b6.vulkan.cache" />
    <Content Include=".godot\shader_cache\CanvasShaderRD\9bdc1125c86af67021aafde8760184618f2961034b221ad5dbe673034858b1f3\8f9335de72e837eeead40640cc01fddc5baf5a7c.vulkan.cache" />
    <Content Include=".godot\shader_cache\CanvasShaderRD\9bdc1125c86af67021aafde8760184618f2961034b221ad5dbe673034858b1f3\b7f8864ed1b8040a3456125a335ae926e257bf47.vulkan.cache" />
    <Content Include=".godot\shader_cache\CanvasShaderRD\9bdc1125c86af67021aafde8760184618f2961034b221ad5dbe673034858b1f3\c2f7efc3419efdd79fabd056897820a83f2ac2c9.vulkan.cache" />
    <Content Include=".godot\shader_cache\CanvasShaderRD\9bdc1125c86af67021aafde8760184618f2961034b221ad5dbe673034858b1f3\ddf1c2fb49f2d96e42d4ffa10cbbb808b4b14063.vulkan.cache" />
    <Content Include=".godot\shader_cache\CanvasShaderRD\9bdc1125c86af67021aafde8760184618f2961034b221ad5dbe673034858b1f3\f3e0fa7ed42441e58a3a071c086d9b7d016da4aa.vulkan.cache" />
    <Content Include=".godot\shader_cache\ClusterDebugShaderRD\d789d0a9a9c2a2b0b6fd18239e92cf44cf6a09f2b3a70fd374d173d50a4be406\8305c75c1294a9f00656f0f14344bb8bedcfe4e7.vulkan.cache" />
    <Content Include=".godot\shader_cache\ClusterRenderShaderRD\1e2e9d959bf97d9428c9bb1d0d014213ffbef36cd795e288cb779c418d8f8370\8305c75c1294a9f00656f0f14344bb8bedcfe4e7.vulkan.cache" />
    <Content Include=".godot\shader_cache\ClusterStoreShaderRD\b1853594c81af4c5dfa70c4136296237d07308f5349bba4d05aaa78ab1522328\8305c75c1294a9f00656f0f14344bb8bedcfe4e7.vulkan.cache" />
    <Content Include=".godot\shader_cache\CopyShaderRD\06416dbb331f92a2c651ac0fcedf5ba066aafc28e591c899ee8a8f8d9167a537\8305c75c1294a9f00656f0f14344bb8bedcfe4e7.vulkan.cache" />
    <Content Include=".godot\shader_cache\CopyToFbShaderRD\516ca1db49f0c89dd5ba5b5f4bb3c26316beafa783d4ea24b25e254d8fc1c428\8305c75c1294a9f00656f0f14344bb8bedcfe4e7.vulkan.cache" />
    <Content Include=".godot\shader_cache\CubeToDpShaderRD\e83b3bb7481a3ffcfdeab999671e26d0ae4d08e0fd57c3368f137e22ad78a1e9\8305c75c1294a9f00656f0f14344bb8bedcfe4e7.vulkan.cache" />
    <Content Include=".godot\shader_cache\CubeToOctmapShaderRD\0a8d46601d323eeb200276345183d0f1446febb4d2b0a580f23bde0fe45e85fa\8305c75c1294a9f00656f0f14344bb8bedcfe4e7.vulkan.cache" />
    <Content Include=".godot\shader_cache\FsrUpscaleShaderRD\9cc3728a0cf1dd7347aee49fe0cbe3009047f904f8dfbbe122c3ae35395cd1a6\8305c75c1294a9f00656f0f14344bb8bedcfe4e7.vulkan.cache" />
    <Content Include=".godot\shader_cache\GiShaderRD\7e279c117959c3fc75fc6bf369f7637e2f2ce5d12eeffb808ab9bc97af873bfc\8305c75c1294a9f00656f0f14344bb8bedcfe4e7.vulkan.cache" />
    <Content Include=".godot\shader_cache\GiShaderRD\d0db97061545374c4aad77fca934cb9bd70afea09ec5692aab7313678fd68fca\8305c75c1294a9f00656f0f14344bb8bedcfe4e7.vulkan.cache" />
    <Content Include=".godot\shader_cache\IntegrateDfgShaderRD\03e8c42f8cb7dde55d058fc79333416ad18fb6bd87bd1fb5d9a6ad14651ddaed\8305c75c1294a9f00656f0f14344bb8bedcfe4e7.vulkan.cache" />
    <Content Include=".godot\shader_cache\LuminanceReduceShaderRD\9f184666cb5c22b85364514685d89dda5bb3f1b85537ad6d60d04e41af01af01\8305c75c1294a9f00656f0f14344bb8bedcfe4e7.vulkan.cache" />
    <Content Include=".godot\shader_cache\MotionVectorsShaderRD\50b078842febfa35329120080e7954028fe9c0f19ee8582e6d69667cc29f6f8c\8305c75c1294a9f00656f0f14344bb8bedcfe4e7.vulkan.cache" />
    <Content Include=".godot\shader_cache\OctmapDownsamplerShaderRD\2232c0d2bbd0444161f6eedf2e402237f04e43c0b0a4182ae60f382701c9e84e\8305c75c1294a9f00656f0f14344bb8bedcfe4e7.vulkan.cache" />
    <Content Include=".godot\shader_cache\OctmapFilterShaderRD\69e12a24310984e7449782cf761a5e21046453235d7d53c5f7ea355f7e0b333e\8305c75c1294a9f00656f0f14344bb8bedcfe4e7.vulkan.cache" />
    <Content Include=".godot\shader_cache\OctmapRoughnessShaderRD\8132261fb0413e611623bf6a3742240101d2f040003a5dee889bbfbb21633b8f\8305c75c1294a9f00656f0f14344bb8bedcfe4e7.vulkan.cache" />
    <Content Include=".godot\shader_cache\ParticlesCopyShaderRD\24d89099f97b1cf1fc7cbbc8f348e37b3ecfeff2344b41cb9355bb1701693999\8305c75c1294a9f00656f0f14344bb8bedcfe4e7.vulkan.cache" />
    <Content Include=".godot\shader_cache\ParticlesShaderRD\b6c7d969adc2c9522906fb5ed230ec231f2f6f4ef9270fc1c37bfe95bf5330bc\07b5904b662900d90454c39c46885098de79aa4c.vulkan.cache" />
    <Content Include=".godot\shader_cache\ResolveShaderRD\cfd5775dd543f5734172100a77ad23587b240dead09ab7049fc1180f7b408828\8305c75c1294a9f00656f0f14344bb8bedcfe4e7.vulkan.cache" />
    <Content Include=".godot\shader_cache\SceneForwardClusteredShaderRD\c2ccf1fba03bf988835dba74b33ff9f9690ef985335908c22dcdd30d4d0def59\078505235c4b1164be3a232fc53717e99ae38384.vulkan.cache" />
    <Content Include=".godot\shader_cache\SceneForwardClusteredShaderRD\c2ccf1fba03bf988835dba74b33ff9f9690ef985335908c22dcdd30d4d0def59\1ba09b8fe53b34cf07e3559908d37d9d8e1e7cd5.vulkan.cache" />
    <Content Include=".godot\shader_cache\SceneForwardClusteredShaderRD\c2ccf1fba03bf988835dba74b33ff9f9690ef985335908c22dcdd30d4d0def59\2dc1b5cfff090b77444337c6816f834532bf6711.vulkan.cache" />
    <Content Include=".godot\shader_cache\SceneForwardClusteredShaderRD\c2ccf1fba03bf988835dba74b33ff9f9690ef985335908c22dcdd30d4d0def59\347259af253e6bbec7ad5c69332af5ca731015aa.vulkan.cache" />
    <Content Include=".godot\shader_cache\SceneForwardClusteredShaderRD\c2ccf1fba03bf988835dba74b33ff9f9690ef985335908c22dcdd30d4d0def59\4d161e027d36dae3228a2fd069c9016607e1d80e.vulkan.cache" />
    <Content Include=".godot\shader_cache\SceneForwardClusteredShaderRD\c2ccf1fba03bf988835dba74b33ff9f9690ef985335908c22dcdd30d4d0def59\766562d5bd8d8fe8f82fbed546ecf33e95f688ff.vulkan.cache" />
    <Content Include=".godot\shader_cache\SceneForwardClusteredShaderRD\c2ccf1fba03bf988835dba74b33ff9f9690ef985335908c22dcdd30d4d0def59\77e28fea868f1d640cf581ded2e966295b75d2d8.vulkan.cache" />
    <Content Include=".godot\shader_cache\SceneForwardClusteredShaderRD\c2ccf1fba03bf988835dba74b33ff9f9690ef985335908c22dcdd30d4d0def59\8c618a1d10342822aa27aecc3b393d09aa8322f6.vulkan.cache" />
    <Content Include=".godot\shader_cache\SceneForwardClusteredShaderRD\c2ccf1fba03bf988835dba74b33ff9f9690ef985335908c22dcdd30d4d0def59\948e921ac3beb78bb2588fa5371e57581afc4819.vulkan.cache" />
    <Content Include=".godot\shader_cache\SceneForwardClusteredShaderRD\c2ccf1fba03bf988835dba74b33ff9f9690ef985335908c22dcdd30d4d0def59\9ae935cd107ff04dc4904f4d9a48208144d11fe5.vulkan.cache" />
    <Content Include=".godot\shader_cache\SceneForwardClusteredShaderRD\c2ccf1fba03bf988835dba74b33ff9f9690ef985335908c22dcdd30d4d0def59\9e61068084fa9878c291e3efa28f7fc19fc6fad3.vulkan.cache" />
    <Content Include=".godot\shader_cache\SceneForwardClusteredShaderRD\c2ccf1fba03bf988835dba74b33ff9f9690ef985335908c22dcdd30d4d0def59\9f7747768f6907bf99462e1b4d32179083107a19.vulkan.cache" />
    <Content Include=".godot\shader_cache\SceneForwardClusteredShaderRD\c2ccf1fba03bf988835dba74b33ff9f9690ef985335908c22dcdd30d4d0def59\a784797763b72ce058effad41b273eb697df9814.vulkan.cache" />
    <Content Include=".godot\shader_cache\SceneForwardClusteredShaderRD\c2ccf1fba03bf988835dba74b33ff9f9690ef985335908c22dcdd30d4d0def59\a8093275b3afef4ee8b8bb9191c8cd99e4e1378b.vulkan.cache" />
    <Content Include=".godot\shader_cache\SceneForwardClusteredShaderRD\c2ccf1fba03bf988835dba74b33ff9f9690ef985335908c22dcdd30d4d0def59\ae3c8e31f908e0df600cc24ef1a7ea00e2995926.vulkan.cache" />
    <Content Include=".godot\shader_cache\SceneForwardClusteredShaderRD\c2ccf1fba03bf988835dba74b33ff9f9690ef985335908c22dcdd30d4d0def59\b600e18e20b53d8932999d48838b29553c586934.vulkan.cache" />
    <Content Include=".godot\shader_cache\SceneForwardClusteredShaderRD\c2ccf1fba03bf988835dba74b33ff9f9690ef985335908c22dcdd30d4d0def59\beb374e34d8d97adb5725df0bfd658fc24c4f80e.vulkan.cache" />
    <Content Include=".godot\shader_cache\SceneForwardClusteredShaderRD\c2ccf1fba03bf988835dba74b33ff9f9690ef985335908c22dcdd30d4d0def59\c4e6dfe2995976d5993c5eeff8c9d5680c538c04.vulkan.cache" />
    <Content Include=".godot\shader_cache\SceneForwardClusteredShaderRD\c2ccf1fba03bf988835dba74b33ff9f9690ef985335908c22dcdd30d4d0def59\de2b6c239d8c3f5684bf02f32d2468f1a12cf624.vulkan.cache" />
    <Content Include=".godot\shader_cache\SceneForwardClusteredShaderRD\c2ccf1fba03bf988835dba74b33ff9f9690ef985335908c22dcdd30d4d0def59\e6d93dcb7095f51274be348f1a89aa0e64db08d3.vulkan.cache" />
    <Content Include=".godot\shader_cache\SceneForwardClusteredShaderRD\c2ccf1fba03bf988835dba74b33ff9f9690ef985335908c22dcdd30d4d0def59\faba017f3680b49e2024b66cc6d194f77217733d.vulkan.cache" />
    <Content Include=".godot\shader_cache\ScreenSpaceReflectionDownsampleShaderRD\e6325ac8b9fb9bcd737992e4214427dca872259a117a5e216101674446c7bbc7\8305c75c1294a9f00656f0f14344bb8bedcfe4e7.vulkan.cache" />
    <Content Include=".godot\shader_cache\ScreenSpaceReflectionFilterShaderRD\da59a83906e0f2e8a22548f117fe20cbea5b3be2e12acbd6b042d77f4eb1c457\8305c75c1294a9f00656f0f14344bb8bedcfe4e7.vulkan.cache" />
    <Content Include=".godot\shader_cache\ScreenSpaceReflectionHizShaderRD\efca221c673612faabbf11b6edf63ce1a9edff2e2832af6582fb7e1effb897fd\8305c75c1294a9f00656f0f14344bb8bedcfe4e7.vulkan.cache" />
    <Content Include=".godot\shader_cache\ScreenSpaceReflectionResolveShaderRD\1fbb748efceb36664d4b25ed0b8b4a1e2f16fe2c8515897b284aafc846e99d5a\8305c75c1294a9f00656f0f14344bb8bedcfe4e7.vulkan.cache" />
    <Content Include=".godot\shader_cache\ScreenSpaceReflectionShaderRD\3bd4227a42d4611084beddc1ec0cc27e071626bd471c96b27001ca3b5be9a5fd\8305c75c1294a9f00656f0f14344bb8bedcfe4e7.vulkan.cache" />
    <Content Include=".godot\shader_cache\SdfgiDebugProbesShaderRD\467fda70c797000ff6af05a8cb526e04218662a9be183aa2a7b46ad2f93cce77\8305c75c1294a9f00656f0f14344bb8bedcfe4e7.vulkan.cache" />
    <Content Include=".godot\shader_cache\SdfgiDebugShaderRD\12dbfdf4517d9a7b37b4faeb432309599b5267d4cc29abaa587181dd5ddcdbc9\8305c75c1294a9f00656f0f14344bb8bedcfe4e7.vulkan.cache" />
    <Content Include=".godot\shader_cache\SdfgiDirectLightShaderRD\0401a0195f37d9da13221e9bb1ca84b6f25642d117306f2939cf9b06d7c187e1\8305c75c1294a9f00656f0f14344bb8bedcfe4e7.vulkan.cache" />
    <Content Include=".godot\shader_cache\SdfgiIntegrateShaderRD\38020518c3928864755a430bbea0312bdfdb8c51075dc2ace5bcddaae36070ad\8305c75c1294a9f00656f0f14344bb8bedcfe4e7.vulkan.cache" />
    <Content Include=".godot\shader_cache\SdfgiPreprocessShaderRD\cd5f8b2fdd3632531a4f732ea1bbb7e2f7ecc333fe8b90b7f7c26d12ee02c55a\8305c75c1294a9f00656f0f14344bb8bedcfe4e7.vulkan.cache" />
    <Content Include=".godot\shader_cache\ShadowFrustumShaderRD\ac0cd9c7a7b5adc08e5e0770aac36764b5ca298a1a412b5d5256e978ac014583\8305c75c1294a9f00656f0f14344bb8bedcfe4e7.vulkan.cache" />
    <Content Include=".godot\shader_cache\SkeletonShaderRD\96ae677d2af41a57b62fdce29c60aed1f841a9f298c7b5dc8c21c330ee4bfbd0\8305c75c1294a9f00656f0f14344bb8bedcfe4e7.vulkan.cache" />
    <Content Include=".godot\shader_cache\SkyShaderRD\5090ce1739a75f47b8eba781fdd25da47220dbf3e500e5864faf5b69a441ea65\0fa1946a11e1cca806ebfe4b3b4ac7f723d8b701.vulkan.cache" />
    <Content Include=".godot\shader_cache\SkyShaderRD\5090ce1739a75f47b8eba781fdd25da47220dbf3e500e5864faf5b69a441ea65\9247dd7bf98483a15ebb05f8c580a398614a07d8.vulkan.cache" />
    <Content Include=".godot\shader_cache\SkyShaderRD\5090ce1739a75f47b8eba781fdd25da47220dbf3e500e5864faf5b69a441ea65\ff1961ca0c4c55a79eb12f819a7b6345801bbbaf.vulkan.cache" />
    <Content Include=".godot\shader_cache\SmaaBlendingShaderRD\28d6881ae8e064e7bb573261202e530fa9cd61edce48d444d046e61ab449ac36\8305c75c1294a9f00656f0f14344bb8bedcfe4e7.vulkan.cache" />
    <Content Include=".godot\shader_cache\SmaaEdgeDetectionShaderRD\87693d8136d46b4b64459dbec139c5405b1cabacb2c3894415b131e8782efb2a\8305c75c1294a9f00656f0f14344bb8bedcfe4e7.vulkan.cache" />
    <Content Include=".godot\shader_cache\SmaaWeightCalculationShaderRD\e920add2247a504ee41de41046b3e7179eb4952232110cb2db89172c537039b8\8305c75c1294a9f00656f0f14344bb8bedcfe4e7.vulkan.cache" />
    <Content Include=".godot\shader_cache\SortShaderRD\a48873e523f14e04dd6158a6a01c5a4e4feb0c7d6714a8c6246ab619a144fa67\8305c75c1294a9f00656f0f14344bb8bedcfe4e7.vulkan.cache" />
    <Content Include=".godot\shader_cache\SpecularMergeShaderRD\2ac072fb5419de33ce27c9014825f16cc6d4060426f4ba73059bc68094b6bfa8\8305c75c1294a9f00656f0f14344bb8bedcfe4e7.vulkan.cache" />
    <Content Include=".godot\shader_cache\SsaoBlurShaderRD\3ff5d62ff4747c7e9e9f6b8205a4437dc39f10b33be8fa73e629fa75fc0e0911\8305c75c1294a9f00656f0f14344bb8bedcfe4e7.vulkan.cache" />
    <Content Include=".godot\shader_cache\SsaoImportanceMapShaderRD\a82018925d702b86595d2166661e310d060917d4e9ba15e44f761060c7b2de83\8305c75c1294a9f00656f0f14344bb8bedcfe4e7.vulkan.cache" />
    <Content Include=".godot\shader_cache\SsaoInterleaveShaderRD\a9a9b2ffc2e8e2f1bd8faf3bef8e282ac615e84e8207b3a6d749db7b41115a81\8305c75c1294a9f00656f0f14344bb8bedcfe4e7.vulkan.cache" />
    <Content Include=".godot\shader_cache\SsaoShaderRD\dbe49ee25c27dfab06f4ceafdc245136a29423ac963551cb1ae3ac2d8a958d4b\8305c75c1294a9f00656f0f14344bb8bedcfe4e7.vulkan.cache" />
    <Content Include=".godot\shader_cache\SsEffectsDownsampleShaderRD\97de52c4017d44cc8bc9cac07ec50ee0d950c87823a123bfe72d66c85e3b3575\8305c75c1294a9f00656f0f14344bb8bedcfe4e7.vulkan.cache" />
    <Content Include=".godot\shader_cache\SsilBlurShaderRD\bc994cf24b385408b444f6309b8b8cc0c300e2add223d358ebac27a5cebd9b2b\8305c75c1294a9f00656f0f14344bb8bedcfe4e7.vulkan.cache" />
    <Content Include=".godot\shader_cache\SsilImportanceMapShaderRD\a3a76b3fc50d25382d0ad7affa6f8aba064612da0acba818798f0d75df747359\8305c75c1294a9f00656f0f14344bb8bedcfe4e7.vulkan.cache" />
    <Content Include=".godot\shader_cache\SsilInterleaveShaderRD\80a9244bd75179adf2d1606cc8a1f6c47b8ac606f9864a1846783007a5847725\8305c75c1294a9f00656f0f14344bb8bedcfe4e7.vulkan.cache" />
    <Content Include=".godot\shader_cache\SsilShaderRD\f18f9d51995393e98ec76d65866e22e4264679600294eff5d76fb86a4d578a4d\8305c75c1294a9f00656f0f14344bb8bedcfe4e7.vulkan.cache" />
    <Content Include=".godot\shader_cache\SubsurfaceScatteringShaderRD\67c90b70b25c773d8dba7dfab0941a884816dc2fc76ea6aab8ab19b0c93d28d4\8305c75c1294a9f00656f0f14344bb8bedcfe4e7.vulkan.cache" />
    <Content Include=".godot\shader_cache\TaaResolveShaderRD\b72c9f24259db22023774f099c134ba5eb5e27abd84e9df475a2ab05404d0abb\8305c75c1294a9f00656f0f14344bb8bedcfe4e7.vulkan.cache" />
    <Content Include=".godot\shader_cache\TexBlitShaderRD\d6c74a83a7053c8f0db4205307d734eb7e49dad4cffc40fefc1c098a20f56c9e\1e8995c9eb0e9b0b053035999de68595c521a33e.vulkan.cache" />
    <Content Include=".godot\shader_cache\TonemapShaderRD\eb9c653c5c11c28b3c78b4b6d2fb70ca4f70e114fea55281aaa38a313893ac6c\8305c75c1294a9f00656f0f14344bb8bedcfe4e7.vulkan.cache" />
    <Content Include=".godot\shader_cache\VolumetricFogProcessShaderRD\20617351d59bc7de5fdd02bae5348fb9c4e0c1ca2e1ca58374bed0f7833ae521\8305c75c1294a9f00656f0f14344bb8bedcfe4e7.vulkan.cache" />
    <Content Include=".godot\shader_cache\VolumetricFogShaderRD\3f2d837801de79c51f543b1445b06125a26772d9cc66b7ab3294925e4c3bdfa9\3377d4ca9d0fc2e16f62596ee37d619e8e7e3f54.vulkan.cache" />
    <Content Include=".godot\shader_cache\VoxelGiDebugShaderRD\e4f59199ebe30ae358ac4d800f8e12818a876bb4b13d27a7a08ff26dc58c4ac8\8305c75c1294a9f00656f0f14344bb8bedcfe4e7.vulkan.cache" />
    <Content Include=".godot\shader_cache\VoxelGiShaderRD\6c4634e4f17397a23696bbc6304a53cc281b742527f6f1883d9548d226e90453\8305c75c1294a9f00656f0f14344bb8bedcfe4e7.vulkan.cache" />
    <Content Include=".godot\shader_cache\VrsShaderRD\0ab6c7454d17aead7529b239657e8420143918f7e497a25a206e1bd0dd65ee07\8305c75c1294a9f00656f0f14344bb8bedcfe4e7.vulkan.cache" />
    <Content Include=".godot\uid_cache.bin" />
    <Content Include="assets\test_card.png" />
    <Content Include="assets\test_card.png.import" />
    <Content Include="Beyond The Worlds.sln" />
    <Content Include="project.godot" />
    <Content Include="src\autoloads\Events.cs.uid" />
    <Content Include="src\cards\AnimationComponent.cs.uid" />
    <Content Include="src\cards\CardBase.cs.uid" />
    <Content Include="src\cards\CardData.cs.uid" />
    <Content Include="src\cards\cards_bases\blood_mage.tres" />
    <Content Include="src\cards\cards_bases\test_card.tres" />
    <Content Include="src\cards\card_base.tscn" />
    <Content Include="src\common\orbital_cam\orbital_cam.gd" />
    <Content Include="src\common\orbital_cam\orbital_cam.gd.uid" />
    <Content Include="src\common\orbital_cam\orbital_cam.tscn" />
    <Content Include="src\levels\level_main.tscn" />
    <Content Include="src\levels\level_test\test_arena.gdshader.uid" />
    <Content Include="src\levels\level_test\test_arena.glb" />
    <Content Include="src\levels\level_test\test_arena.glb.import" />
    <Content Include="src\levels\level_test\test_arena.tscn" />
    <Content Include="src\player\PlayerHealth.cs.uid" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include=".git\refs\tags\" />
    <Folder Include=".godot\shader_cache\Fsr2AccumulatePassShaderRD\7e3388306b8b814b99d86d08901cb85411ed7874055da2a9ac7169350663fb24\" />
    <Folder Include=".godot\shader_cache\Fsr2AutogenReactivePassShaderRD\15ad4238e088069ce62513ace17fccddc0a031c33651859b6182b345c260417d\" />
    <Folder Include=".godot\shader_cache\Fsr2ComputeLuminancePyramidPassShaderRD\ea30b9cf2586f5efa8adb0623d631dca2e08fcbffc511d15e430309048b62811\" />
    <Folder Include=".godot\shader_cache\Fsr2DepthClipPassShaderRD\636f74877424985a3491c9f4aacd1e6a3bc5e7c47be7f5154bd8dbe63a109a6b\" />
    <Folder Include=".godot\shader_cache\Fsr2LockPassShaderRD\e1f2a67ded37287c61ec8c8e1a93c5ef2f559e6cf8d3ee502740645f0ffb656e\" />
    <Folder Include=".godot\shader_cache\Fsr2RcasPassShaderRD\0a53240e7518f90b514d903b4572aedbe9103d60b7d67bc733918003c5971ca1\" />
    <Folder Include=".godot\shader_cache\Fsr2ReconstructPreviousDepthPassShaderRD\7bb138b53460583c5620036572edf3406f00775acd6cc00d6f13210abf2b576a\" />
    <Folder Include=".godot\shader_cache\Fsr2TcrAutogenPassShaderRD\688ab227efbf4151af5ade3b8ebcdde4ec62216e405d7f11e51afb3fe8ad183f\" />
    <Folder Include=".godot\shader_cache\SceneForwardClusteredShaderRD\3b57f606108ded8878ba68c5c59a308a1978b2ad7788fd022d00660d3b950daa\" />
    <Folder Include=".godot\shader_cache\SceneForwardClusteredShaderRD\63029fb9eee2470d331573517cb058629ab991547b2cce9159a56a2524bf6ae4\" />
    <Folder Include=".godot\shader_cache\SceneForwardClusteredShaderRD\f992b32f15c3b360ad9fb2499081c03f580cd3bcd5c852dae5a18e441f4dcc90\" />
    <Folder Include=".godot\shader_cache\VolumetricFogProcessShaderRD\2a432b0c26391eeeb6b041b1f390a109d3963104cd63635466aa425cb951d2c3\" />
    <Folder Include=".godot\shader_cache\VolumetricFogProcessShaderRD\7c889aecf88c66deff81aaa463066acbcc812aea1d2d5abed24f7d80232e0d6d\" />
    <Folder Include=".godot\shader_cache\VolumetricFogProcessShaderRD\88861d94108be6765a4f5a12bf3d2c020518bf6cea2d75339515d8bfcfa33cf0\" />
    <Folder Include=".godot\shader_cache\VolumetricFogShaderRD\1e2a055ad4b80929a577ea9e61f3c272034f521a8e1d3663211a5bf3696e28e8\" />
    <Folder Include=".godot\shader_cache\VolumetricFogShaderRD\59d8d6bad9e8029584ea03285e0d55a37dbda33a837032e499276ba2d0382d15\" />
    <Folder Include=".godot\shader_cache\VolumetricFogShaderRD\fb13248b2f1e9f68baf9d79451a7d5e06296b2ca4920c889f0cfa13da6ecf28c\" />
  </ItemGroup>
</Project>