<Project Sdk="Godot.NET.Sdk/4.7.0">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <TargetFramework Condition=" '$(GodotTargetPlatform)' == 'android' ">net9.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <RootNamespace>BeyondTheWorlds</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Content Include=".gitattributes" />
    <Content Include=".gitignore" />
    <Content Include="Beyond The Worlds.sln" />
    <Content Include="project.godot" />
    <Content Include="src\autoloads\Events.cs.uid" />
    <Content Include="src\cards\CardBase.cs.uid" />
    <Content Include="src\cards\CardData.cs.uid" />
    <Content Include="src\cards\HandManager.cs.uid" />
    <Content Include="src\common\orbital_cam\orbital_cam.gd" />
    <Content Include="src\common\orbital_cam\orbital_cam.gd.uid" />
    <Content Include="src\common\orbital_cam\orbital_cam.tscn" />
    <Content Include="src\levels\level_main.tscn" />
    <Content Include="src\levels\level_test\test_arena.gdshader.uid" />
    <Content Include="src\levels\level_test\test_arena.glb" />
    <Content Include="src\levels\level_test\test_arena.glb.import" />
    <Content Include="src\levels\level_test\test_arena.tscn" />
    <Content Include="src\player\PlayerHealth.cs.uid" />
  </ItemGroup>
</Project>